---
title: "Supermarket presence by income bracket in Buffalo, NY"
author: Eric Hughes
---

# Introduction

Access to healthy food is not equal across all regions. Many factors influence food access such as vehicle access, proximity of quality grocery retailers, and income. The most basic measure of food access is proximity to supermarkets. Supermarkets have the resources to carry a wide range of produce and have affordable prices which makes their presence a good measure of local food security.

This project aims to look at Buffalo resident's proximity to supermarkets by their median income. To do this, Buffalo residents will be grouped together in five income brackets and the average distance to a supermarket for each bracket will be calculated for various modes of transportation. Demographic information about each bracket will also be examined to better explain the food disparity phenomenon.  


# Materials and methods

- US Census Bureau will provide census tract data of median household income, as well as demographic data, for Buffalo

- Open Data Buffalo for Neighborhood Boundary Shapefile

- ESRI Business Analyst will provide supermarket data

# Proposed methods


- Data cleaning and processing

- Plot data for median household income

- Plot supermarket data

- Clip data to Buffalo boundary

- Use the dodgr package to determine travel distances 

- Analyze and plot the data for each mode of transport 


# Packages
```
library(tidyverse)
library(ggplot2)
library(ggmap)
library(maptools)
library(ggthemes)
library(plyr)
library(dplyr)
library(grid)
library(gridExtra)
library(scales)
library(sp)
library(sf)
library(RColorBrewer)
library(dodgr)
library(leaflet)
```

# Results

[~200 words]

Tables and figures (maps and other graphics) are carefully planned to convey the results of your analysis. Intense exploration and evidence of many trials and failures. The author looked at the data in many different ways before coming to the final presentation of the data.

Show tables, plots, etc. and describe them.

# Conclusions

[~200 words]

Clear summary adequately describing the results and putting them in context. Discussion of further questions and ways to continue investigation.

# References

All sources are cited in a consistent manner
